apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: asoc

resources:
  - namespace.yaml
  - public-urls.yaml
  - postgres.yaml
  - kafka.yaml
  - workloads.yaml
  - frontend.yaml
  - ingress.yaml

configMapGenerator:
  - name: asoc-migrations
    options:
      disableNameSuffixHash: true
    files:
      - ../../migrations/001_reference_schema.sql
      - ../../migrations/002_processing_schema.sql
      - ../../migrations/003_integration_schema.sql
      - ../../migrations/004_demo_seed.sql
      - ../../migrations/005_demo_cwe_alias.sql
